#!/bin/bash

SOURCE_BRANCH="master"
SOURCE_COMMIT=$(git ls-remote https://github.com/AlexeyAB/darknet.git HEAD | awk '{ print $1 }')
VAR=$DOCKER_TAG

docker build \
  --build-arg CONFIG=$VAR \
  --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
  -t $IMAGE_NAME -f $DOCKERFILE_PATH .
